project:
  type: website
  
lang: de-CH

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Projekt
      - href: biodiversity_footprint.qmd
        text: Biodiversity-Footprint
format:
  html:
    theme: flatly
    grid:
      body-width: 1200px
    #css: bootstrap.css
    #toc: true
