project:
  type: website
  
lang: de-CH

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Projekt
      - href: app.qmd
        text: Biodiversity-Footprint
format:
  html:
    theme: flatly
    grid:
      body-width: 1000px
    #css: bootstrap.css
    #toc: true
